[theme]
base                     = "dark"
primaryColor             = "#cba6f7"
backgroundColor          = "#0e1117"
secondaryBackgroundColor = "#1e1e2e"
textColor                = "#cdd6f4"

[browser]
gatherUsageStats = false
